title: Mestara
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_type: full-width
style: classic
palette: blue
mode: light
base_font: serif
header:
  logo: images/Logo Mestara.png
  has_primary_nav: true
  primary_nav_links:
    - label: Program
      url: /features
      style: link
    - label: About
      url: /about
      style: link
    - label: Blog
      url: /blog
      style: link
    - label: Style Guide
      url: /style-guide
      style: link
  has_secondary_nav: true
  secondary_nav_links:
    - label: Contact
      url: /contact
      style: link
    - label: Get Started
      url: /pricing
      style: primary
  has_anncmnt: true
  anncmnt_content: >-
    Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn
    More](/pricing/)**
  anncmnt_align: left
  anncmnt_is_home_only: true
  anncmnt_has_close: true
  anncmnt_id: new-features
footer:
  logo: images/Logo Mestara.png
  logo_alt: DIY logo
  has_primary_nav: true
  primary_nav_title: Company
  primary_nav_links:
    - label: About
      url: /about
      style: link
    - label: Style Guide
      url: /style-guide
      style: link
  has_secondary_nav: true
  secondary_nav_title: Blog
  secondary_nav_links:
    - label: News
      url: /blog/category/news
      style: link
    - label: General
      url: /blog/category/general
      style: link
    - label: Tutorials
      url: /blog/category/tutorials
      style: link
  has_tertiary_nav: true
  tertiary_nav_title: Legal
  tertiary_nav_links:
    - label: Terms & Conditions
      url: /terms-conditions
      style: link
    - label: Privacy Policy
      url: /privacy-policy
      style: link
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      style: link
      has_icon: true
      icon: twitter
      icon_position: center
      new_window: true
    - label: GitHub
      url: 'https://github.com/'
      style: link
      has_icon: true
      icon: github
      icon_position: center
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: link
      has_icon: true
      icon: linkedin
      icon_position: center
      new_window: true
    - label: YouTube
      url: 'https://www.youtube.com/'
      style: link
      has_icon: true
      icon: youtube
      icon_position: center
      new_window: true
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>. Create yours <a
    href="https://app.stackbit.com/create?theme=diy&utm_source=deployed-footer"
    target="_blank" rel="noopener">now</a>
sass:
  indentWidth: 4
  style: expanded
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
domain: 'https://mestara-034cd.netlify.app'
